config/routes.rb
Rails.application.routes.draw do

  resources :showcars
  devise_for :users
  devise_for :clients
  resources :templates




  root 'welcome#index'

  get 'servicios/' => 'templates#servicios', as: :servicios
  get 'conocenos/' => 'templates#conocenos', as: :conocenos
  get 'contactanos/' => 'templates#contactanos', as: :contactanos
  get 'CMS/' => 'templates#CMS', as: :CMS
  get 'profile/' => "users#profile"







end

app/models/car.rb
class Car < ActiveRecord::Base
end

app/models/car_image.rb
class CarImage < ActiveRecord::Base
    belongs_to: Car
end

app/models/citation.rb
class Citation < ActiveRecord::Base
  belongs_to: User
  belongs_to: Car
end

app/models/client.rb
class Client < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/section.rb
class Section < ActiveRecord::Base
end

app/models/showcar.rb
class Showcar < ActiveRecord::Base
  validates :name, uniqueness: true  
end

app/models/template.rb
class Template < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :configure_devise_permitted_parameters, if: :devise_controller?
  before_action :init

protected

  def configure_devise_permitted_parameters
      registration_params = [:name, :email, :password, :password_confirmation]

      if params[:action] == 'update'
        devise_parameter_sanitizer.for(:account_update) {
          |u| u.permit(registration_params << :current_password)
        }
      elsif params[:action] == 'create'
        devise_parameter_sanitizer.for(:sign_up) {
          |u| u.permit(registration_params)
        }
      end
  end

  def init
    @views = Template.all
  end

end

app/controllers/showcars_controller.rb
class ShowcarsController < ApplicationController
  before_action :set_showcar, only: [:show, :edit, :update, :destroy]
  #before_action :init
  before_action :initvar

  @initialized = false

  def initvar
    @views = Template.all
  end


  #i'm creating 3 cars to the showcar
  def init

        newCar = Showcar.create(name: "Reventon",
        description: "It was the most expensive Lamborghini road car until the Lamborghini Sesto Elemento was launched, costing two million dollars (~$1.5 million, or ~£840,000). Its top speed was recorded in UAE at 221 miles per hour (355.7 km/h).",
        photo_link: "reventon.jpg")
        newCar.save

        newCar = Showcar.create(name: "Diablo",
        description: "The Lamborghini Diablo is a high-performance mid-engined sports car that was built by Italian automaker Lamborghini between 1990 and 2001. It was the first Lamborghini capable of attaining a top speed in excess of 200 miles per hour (320 km/h). After the end of its production run in 2001, the Diablo was replaced by the Lamborghini Murciélago. Diablo means @\"devil@\" in Spanish.",
        photo_link: "diablo.jpg")
        newCar.save

        newCar = Showcar.create(name: "Veneno",
        description: "Lamborthini Veneno is consistently focused on optimum aerodynamics and cornering stability, giving the Veneno the real dynamic experience of a racing prototype, yet it is full homologated for the road.",
        photo_link: "veneno.jpg")
        newCar.save

  end
  # GET /showcars
  # GET /showcars.json
  def index
    @showcars = Showcar.all
  end

  # GET /showcars/1
  # GET /showcars/1.json
  def show
  end

  # GET /showcars/new
  def new
    @showcar = Showcar.new
  end

  # GET /showcars/1/edit
  def edit
  end

  # POST /showcars
  # POST /showcars.json
  def create
    @showcar = Showcar.new(showcar_params)

    respond_to do |format|
      if @showcar.save
        format.html { redirect_to @showcar, notice: 'Showcar was successfully created.' }
        format.json { render :show, status: :created, location: @showcar }
      else
        format.html { render :new }
        format.json { render json: @showcar.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /showcars/1
  # PATCH/PUT /showcars/1.json
  def update
    respond_to do |format|
      if @showcar.update(showcar_params)
        format.html { redirect_to @showcar, notice: 'Showcar was successfully updated.' }
        format.json { render :show, status: :ok, location: @showcar }
      else
        format.html { render :edit }
        format.json { render json: @showcar.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /showcars/1
  # DELETE /showcars/1.json
  def destroy
    @showcar.destroy
    respond_to do |format|
      format.html { redirect_to showcars_url, notice: 'Showcar was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_showcar
      @showcar = Showcar.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def showcar_params
      params.require(:showcar).permit(:name, :description, :photo_link)
    end
end

app/controllers/templates_controller.rb
class TemplatesController < ApplicationController
  before_action :set_template, only: [:show, :edit, :update, :destroy]

  # GET /templates
  # GET /templates.json
  def index
    @templates = Template.all
  end

  # GET /templates/1
  # GET /templates/1.json
  def show
  end

  # GET /templates/new
  def new
    @template = Template.new
  end

  # GET /templates/1/edit
  def edit
  end

  # POST /templates
  # POST /templates.json
  def create
    @template = Template.new(template_params)

    respond_to do |format|
      if @template.save
        format.html { redirect_to @template, notice: 'Template was successfully created.' }
        format.json { render :show, status: :created, location: @template }
      else
        format.html { render :new }
        format.json { render json: @template.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /templates/1
  # PATCH/PUT /templates/1.json
  def update
    respond_to do |format|
      if @template.update(template_params)
        format.html { redirect_to @template, notice: 'Template was successfully updated.' }
        format.json { render :show, status: :ok, location: @template }
      else
        format.html { render :edit }
        format.json { render json: @template.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /templates/1
  # DELETE /templates/1.json
  def destroy
    @template.destroy
    respond_to do |format|
      format.html { redirect_to templates_url, notice: 'Template was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def servicios
  end

  def conocenos
  end

  def contactanos
  end

  def CMS
    @showcars = Showcar.all
    @templates = Template.all
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_template
      @template = Template.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def template_params
      params.require(:template).permit(:title, :content, :urlImage)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  # GET /users
  def index
    @users = User.all
    @userCreation = User.new
  end

  #GET /users/:id
  def show
    @users = User.find(params[:id])
  end


  #POST /users
  def create

    uEmail = params[:user][:email]

    if !User.where(email: uEmail).exists?
      @user = User.new(name: params[:user][:name], email: params[:user][:email], password: params[:user][:password])
      @user.save
    end

    redirect_to index
  end

  def profile
    render "devise/profile"
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/showcars_helper.rb
module ShowcarsHelper
end

app/helpers/templates_helper.rb
module TemplatesHelper
end

app/helpers/user_test_helper.rb
module UserTestHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
	<title>IlCastello</title>




	<link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">

	<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
	<script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>

	<script src="http://code.jquery.com/jquery-latest.js"></script>

   	<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  	<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>


</head>

<body style="padding:0px; margin:0px; background-color:black;font-family:Arial, sans-serif">

	<span class="ir-arriba glyphicon glyphicon-arrow-up" style="display: block;"></span>
		<div class ="contenido">
			<nav class="navbar navbar-inverse" id="gen-nav">
			  <div id ="nav-link" class="container-fluid">
				<div class="navbar-header .nav-link">
				  <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
				  </button>

				  <a class="navbar-brand" href="/" style="border-bottom: solid #222222;"><img WIDTH=40 HEIGHT=41 src="http://cdn.lamborghini.com/templates/main/Resources/Public/src/img/logo.png" style="margin-top: -10px;"></a>

				</div>

						<div class="collapse navbar-collapse" id="myNavbar">
						  <ul class="nav navbar-nav .nav-link" style="font-size: 127%;">

							<li class="active"><a href="/" style="border-bottom:solid 3px #F3C848"><span class="glyphicon glyphicon-home"></span>&nbsp;Home</a></li>
							<li><a href="showcars" style="border-bottom: solid #222222;"><span class="glyphicon glyphicon-book"></span>&nbsp;Cars</a></li>
							<li><a href="servicios" style="border-bottom: solid #222222;"><span class="glyphicon glyphicon-wrench"></span>&nbsp;Services</a></li>
							<li><a href="conocenos" style="border-bottom: solid #222222;"><span class="glyphicon glyphicon-hand-up"></span>&nbsp;About us</a></li>
							<li><a href="contactanos" style="border-bottom: solid #222222;"><span class="glyphicon glyphicon-phone-alt"></span>&nbsp;Contact</a></li>
							<%if @views.size > 0%>
									<% @views.each do |view|%>
										<li><%=link_to view.title, controller: "templates", action: "show", id: view.id, class: "bar-item"%></li>
									<%end%>
							<%end%>
							<% if user_signed_in?%>
								<li><a href="CMS" style="border-bottom: solid #222222;"><span class="glyphicon glyphicon-pencil"></span>&nbsp;CMS</a></li>
							<%end%>
						  </ul>

						  <%= render "partials/session"%>
						</div>


			  </div>
			</nav>
			<hr id ="divisor">

			<!--<p class="notice"><%= notice %></p>
		  <p class="alert"><%= alert %></p>-->

		<%= yield %>

	</div>

	<div id="footer">
			<ul class="icons">
				<li><a href="#" class="icon fa-twitter"><span class="label">Twitter</span></a></li>
				<li><a href="#" class="icon fa-facebook"><span class="label">Facebook</span></a></li>
				<li><a href="#" class="icon fa-github"><span class="label">GitHub</span></a></li>
				<li><a href="#" class="icon fa-linkedin"><span class="label">LinkedIn</span></a></li>
				<li><a href="#" class="icon fa-google-plus"><span class="label">Google+</span></a></li>
			</ul>
			<!-- Copyright -->
			<div class="copyright">
				<ul class="menu">
					<li>&copy; Il Castello. All rights reserved</li><li>Design: <a href="http://thevirtualcastle.com/">Virtual Castle</a></li>
				</ul>
			</div>

		</div>
	</div>
	<script>
		$(document).ready(function(){
			//$("#gen-nav").css("width", "100%")
			//$("#gen-nav").css("position","fixed")

			$('.ir-arriba').click(function(){
				$('body, html').animate({
					scrollTop: '0px'
				},300 );
			});

			$(window).scroll(function(){
				if ($(this).scrollTop() > 0){
					$('.ir-arriba').slideDown(300);
				} else {
					$('.ir-arriba').slideUp(300);
				};
			});
		});
	</script>



</body>
</html>

app/views/partials/_cars_view.html.erb
  <section class="wrapper style1">
          <div class="container">
              <div class="row">
                   <% @showcars.each do |showc| %>
                        <section class="6u 12u(narrower)" style="border: solid 3px;border-style: groove;border-radius: 15px; margin-left: 2%;">
                            <div class="box post">
                              <%= link_to image_tag("showcar/" << showc.photo_link), root_path, :class  => "image left" %>
                                <div class="inner" style="margin-left: 52%;">
                                    <h3><%= showc.name %></h3>
                                    <p><%= showc.description%></p>
                                 </div>
                            </div>
                          </section>

                      <%end%>
                  </div>
              </div>

app/views/partials/_cms_showcar.html.erb
<p id="notice"><%= notice %></p>
<div class="inner-cms">

  <h1 class="cms-h1">Listing Showcar</h1>
  <div class="row">


        <div class="col-md-1">Name</div>
        <div class="col-md-7">Description</div>
        <div class="col-md-1">Photo link</div>
        <div class="col-md-3"></div>
    </div>

    <br>

      <% @showcars.each do |showcar| %>

        <div class="row">
          <div class="col-md-1"><%= showcar.name %></div>
          <div class="col-md-7"><%= showcar.description %></div>
          <div class="col-md-1"><%= showcar.photo_link %></div>
          <div class="col-md-3">
            <div class="row">
            <div class="col-md-4"><%= link_to 'Show', showcar , class: "show-button"%></div>
            <div class="col-md-4"><%= link_to 'Edit', edit_showcar_path(showcar), class: "edit-button" %></div>
            <div class="col-md-4"><%= link_to 'Destroy', showcar, method: :delete, data: { confirm: 'Are you sure?' }, class: "destroy-button" %></div>
              </div>
          </div>
        </div>
        <hr>
      <% end %>

<br>
      <div class="">
          <%= link_to 'New Showcar', new_showcar_path, class: "newshowcar-button" %>
      </div>
  </div>

<br>

app/views/partials/_cms_views.html.erb
<p id="notice"><%= notice %></p>
<div class="inner-cms">

  <h1 class="cms-h1">Listing Views</h1>
  <div class="row">


        <div class="col-md-1">Title</div>
        <div class="col-md-7">Content</div>
        <div class="col-md-1">UrlImage</div>
        <div class="col-md-3"></div>
    </div>

    <br>

    <% @templates.each do |template| %>

        <div class="row">
              <div class="col-md-1"><%= template.title %></div>
              <div class="col-md-7">  <%= template.content %></div>
              <div class="col-md-1"><%= template.urlImage %></div>
              <div class="col-md-3">
                  <div class="row">
                    <div class="col-md-4"><%= link_to 'Show', template %></div>
                    <div class="col-md-4"><%= link_to 'Edit', edit_template_path(template) %></div>
                    <div class="col-md-4"><%= link_to 'Destroy', template, method: :delete, data: { confirm: 'Are you sure?' } %></div>
                  </div>
              </div>
        </div>
        <hr>
    <% end %>


    <br>
          <div class="">
              <%= link_to 'New Template', new_template_path, class: "newshowcar-button" %>
          </div>
      </div>

    <br>

app/views/partials/_session.html.erb
<ul class="nav navbar-nav navbar-right">
  <% if !user_signed_in? %>
    <li><<span class="glyphicon glyphicon-user"></span> <%= link_to "Sign Up", new_user_registration_path %> </li>
    <li><span class="glyphicon glyphicon-log-in"></span> <%= link_to "Log In", new_user_session_path %> </li>
    <%else%>

    <li><%= link_to current_user.name, profile_path, :style=>"border-bottom:black"%> </li>
    <!--
    <li><span class="glyphicon glyphicon-user"></span> Saludos, <%= current_user.name %></li>-->
    <li><span class="glyphicon glyphicon-log-in"></span> <%= link_to "Sign out", destroy_user_session_path, :method => :delete %> </li
  <%end%>
</ul>

app/views/showcars/_form.html.erb
<%= form_for(@showcar) do |f| %>
  <% if @showcar.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@showcar.errors.count, "error") %> prohibited this showcar from being saved:</h2>

      <ul>
      <% @showcar.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="imageView">
    <%if @showcar.photo_link != nil %>
      <%= link_to image_tag("showcar/" << @showcar.photo_link), root_path, :class  => "image left" %>
    <%end%>
  </div>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name , class: "form-control"%>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_field :description , class: "form-control"%>
  </div>
  <div class="field">
    <%= f.label :photo_link %><br>
    <%= f.text_field :photo_link , class: "form-control"%>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/showcars/edit.html.erb
<div class="row center-xs">
  <div class="col-xs-8 col-md-6 ">
    <div class="box text-left">
        <h1>Editing Showcar</h1>

        <%= render 'form' %>

        <%= link_to 'Show', @showcar %> |
        <%= link_to 'Back', :controller => 'templates', :action => 'CMS' %>
    </div>
  </div>
</div>

app/views/showcars/index.html.erb
<p id="notice"><%= notice %></p>

<div class="jumbotron" style ="text-align:center;background: linear-gradient(#0E0D0A, #CEA420);/* padding-bottom: 0px; *//* color: #FDC725; */border-bottom: solid 4px;color: #FDC725;";>
   <h1 style="margin-bottom: 3%;color: white;">Our Cars - Il Castello</h1>
   <h4 style="color:white">Lamborghini's Official Dealer</h4>
</div>

<%= render "partials/cars_view"%>

 </section>
 <script>
   $(document).ready(function(){
      //$(".active").css("")
      $(".active").removeClass("active");
      var li = $($(".navbar-nav")[0]).find("li")[1];
      $(li).addClass("active");

   });

 </script>

app/views/showcars/new.html.erb
<div class="row center-xs">
  <div class="col-xs-8 col-md-6 ">
    <div class="box text-left">
        <h1>New Showcar</h1>

        <%= render 'form' %>

        <%= link_to 'Back', :controller => 'templates', :action => 'CMS' %>
    </div>
  </div>
</div>

app/views/showcars/show.html.erb
<p id="notice"><%= notice %></p>

<div class="imageView">
  <%if @showcar.photo_link != nil %>
    <%= link_to image_tag("showcar/" << @showcar.photo_link), root_path, :class  => "image left", :width => 400, :height => 300%>
  <%end%>
</div>

<div class="show-each">

  <p>
    <strong>Name:</strong>
    <%= @showcar.name %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= @showcar.description %>
  </p>

  <p>
    <strong>Photo link:</strong>
    <%= @showcar.photo_link %>
  </p>

  <%= link_to 'Edit', edit_showcar_path(@showcar) %> |
  <%= link_to 'Back', :controller => 'templates', :action => 'CMS' %>

</div>

app/views/templates/CMS.html.erb
  <style>
              /*
           * Base structure
           */

          /* Move down content because we have a fixed navbar that is 50px tall */
          body {
            padding-top: 50px;
          }


          /*
           * Global add-ons
           */

          .sub-header {
            padding-bottom: 10px;
            border-bottom: 1px solid #eee;
          }

          /*
           * Top navigation
           * Hide default border to remove 1px line.
           */
          .navbar-fixed-top {
            border: 0;
          }

          /*
           * Sidebar
           */

          /* Hide for mobile, show later */
          .sidebar {
            display: none;
          }
          @media (min-width: 768px) {
            .sidebar {
              position: fixed;
              top: 51px;
              bottom: 0;
              left: 0;
              z-index: 1000;
              display: block;
              padding: 20px;
              overflow-x: hidden;
              overflow-y: auto; /* Scrollable contents if viewport is shorter than content. */
              background-color: #f5f5f5;
              border-right: 1px solid #eee;
            }
          }

          /* Sidebar navigation */
          .nav-sidebar {
            margin-right: -21px; /* 20px padding + 1px border */
            margin-bottom: 20px;
            margin-left: -20px;
          }
          .nav-sidebar > li > a {
            padding-right: 20px;
            padding-left: 20px;
          }
          .nav-sidebar > .active > a,
          .nav-sidebar > .active > a:hover,
          .nav-sidebar > .active > a:focus {
            color: #fff;
            background-color: #428bca;
          }


          /*
           * Main content
           */

          .main {
            padding: 110px;
          }
          @media (min-width: 768px) {
            .main {
              padding-right: 0px;
              padding-left: 40px;
            }
          }
          .main .page-header {
            margin-top: 30;
          }


          /*
           * Placeholder dashboard ideas
           */

          .placeholders {
            margin-bottom: 30px;
            text-align: center;
          }
          .placeholders h4 {
            margin-bottom: 0;
          }
          .placeholder {
            margin-bottom: 20px;
          }
          .placeholder img {
            display: inline-block;
            border-radius: 50%;
          }

  </style>


    <div class="container-fluid" style="padding-top: 0%;">
      <div class="row" style="background-color:white; min-height: 500px;width: 106%;margin-top:0%;">
        <div class="col-sm-3 col-md-2 sidebar" style="top: 11%;background-color: #000000;max-height: 100%;border: solid 4px black;border-top-color: #E1AF2D;">
          <ul class="nav nav-sidebar" style="color: #F3C848;">
            <li class="active">CMS</li>
            <li><a href="#" onclick = "cambiarCMS('0')" style="color: #CF9207;border-bottom: solid;">Showcar</a></li>
            <li><a href="#" onclick = "cambiarCMS('1');" style="color: #CF9207;border-bottom: solid;">Views</a></li>
            <li><a href="#" onclick = "cambiarCMS('2');" style="color: #CF9207;border-bottom: solid;">Users / Roles</a></li>
            <li><a href="#" onclick = "cambiarCMS('3');" style="color: #CF9207;border-bottom: solid;">Citations</a></li>
          </ul>
        </div>
        <div class="col-sm-12 col-sm-offset-3 col-md-12 col-md-offset-2 main" >

          <div class="row placeholders" id="content">

            <div class="col-xs-12 col-sm-9 placeholder current">
              <!--<h2 class="sub-header">Showcar</h2>
              <h4>Label 1</h4>
              <span class="text-muted">Something else 1</span>-->
              <%= render "partials/cms_showcar"%>
            </div>

            <div class="col-xs-12 col-sm-9 placeholder" style="display:none">
              <!--<h2 class="sub-header">Showcar</h2>
              <h4>Label 1</h4>
              <span class="text-muted">Something else 1</span>-->
              <%= render "partials/cms_views"%>
            </div>

            <div class="col-xs-6 col-sm-3 placeholder" style="display:none">
                <h2 class="sub-header">title 3</h2>
                <h4>Label 3</h4>
                <span class="text-muted">Something else 3</span>
            </div>

            <div class="col-xs-6 col-sm-3 placeholder" style="display:none">
                <h2 class="sub-header">title 4</h2>
                <h4>Label 4</h4>
                <span class="text-muted">Something else 3</span>
            </div>

          </div>
        </div>
      </div>
    </div>

    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
    <script>window.jQuery || document.write('<script src="../../assets/js/vendor/jquery.min.js"><\/script>')</script>
    <script src="../../dist/js/bootstrap.min.js"></script>
    <!-- Just to make our placeholder images work. Don't actually copy the next line! -->
    <script src="../../assets/js/vendor/holder.min.js"></script>
    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <script src="../../assets/js/ie10-viewport-bug-workaround.js"></script>
    <script>
      $(document).ready(function(){
           //$(".active").css("")
        //   $("#gen-nav").css("position","fixed");
          //      $("#gen-nav").css("width", "100%");

           $(".active>a").css("border-bottom","solid 4px #222222");
           $(".active").removeClass("active");
           var li = $($(".navbar-nav")[0]).find("li")[5];
           $(li).addClass("active");
            $(".active>a").css("border-bottom","solid 3px #F3C848");

        });

      function cambiarCMS(idx){
         $($("#content").find(".current")).fadeOut();
         setTimeout(function(){$($("#content").children()[idx]).fadeIn().addClass("current");},500);
      }

  </script>

app/views/templates/_form.html.erb
<%= form_for(@template) do |f| %>
  <% if @template.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@template.errors.count, "error") %> prohibited this template from being saved:</h2>

      <ul>
      <% @template.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title , class: "form-control"%>
  </div>
  <div class="field">
    <%= f.label :content %><br>
    <%= f.text_field :content , class: "form-control"%>
  </div>
  <div class="field">
    <%= f.label :urlImage %><br>
    <%= f.text_field :urlImage , class: "form-control"%>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/templates/edit.html.erb
<div class="row center-xs">
  <div class="col-xs-8 col-md-6 ">
    <div class="box text-left">
      <h1>Editing Template</h1>

        <%= render 'form' %>

        <%= link_to 'Show', @template %> |
        <%= link_to 'Back', :controller => 'templates', :action => 'CMS' %>
          </div>
      </div>
</div>

app/views/templates/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Templates</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Content</th>
      <th>Urlimage</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @templates.each do |template| %>
      <tr>
        <td><%= template.title %></td>
        <td><%= template.content %></td>
        <td><%= template.urlImage %></td>
        <td><%= link_to 'Show', template %></td>
        <td><%= link_to 'Edit', edit_template_path(template) %></td>
        <td><%= link_to 'Destroy', template, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Template', new_template_path %>

app/views/templates/show.html.erb
<p id="notice"><%= notice %></p>
<div class="row center-xs">
  <div class="col-xs-8 col-md-6 ">
    <div class="box text-left">
        <div class="imageView" style="height:500px; width:850px; ">
          <%if @template.urlImage != nil %>
            <%= link_to image_tag("" << @template.urlImage), root_path, :class  => "image left" %>
          <%end%>
        </div>


      <div class="show-view">

        <h1>
          <%= @template.title %>
        </h1>

        <p>
          <%= @template.content %>
        </p>

      </div>
    </div>
  </div>
</div>



<!--<%= link_to 'Edit', edit_template_path(@template) %> |
<%= link_to 'Back', :controller => 'templates', :action => 'CMS' %>-->